import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/HeaderComponent";
import { AppWrapper } from "@/context/DataContext";
import DesktopSideComponent from "@/components/DesktopSideComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Itinera-IO",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icons/itineraIcon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWrapper>
          <HeaderComponent />
          <DesktopSideComponent/>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
